
export const blogData = [
  {
    id: 1,
    title: 'Altaneo finance',
    img: '../../../public/assets/img/investor3.png', 
    oneLine: 'Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of...',
    description:"Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of thousands killed during 2020. It has created economic chaos and caused great damage to firms, their customers, and their suppliers. A critical need for firms is to maintain their financial liquidity to facilitate demand and supply challenges. Across the supply chain, organizations have been forced to reduce staffing to cut costs. These cuts resulted in a dramatic fall in demand for goods and services. For some industrial sectors such as hospitality, tourism and airlines, most revenues were wiped out. Managers had to take drastic decisions to maintain liquidity to survive which resulted in eroding cash reserves, further headcount reductions, reduced expenditures and postponing capital investments. Late customer payments increase in bad debt, and restrictive bank lending practices compounded cash flow problems and decreased liquidity. These problems led to an increased risk of insolvency and resulted in more employee layoffs. Firms found themselves in a downward spiral. A key strategic priority for companies is ensuring that they can meet their net working capital (NWC) needs, where NWC = current assets – current liabilities. Supply chain financing (SCF) is an approach that builds on traditional trade finance solutions to help organizations manage its net working capital more flexibly and at a lower rate of interest than is normally available to a supplier. Suppliers are able to sell their approved invoices to a bank or financial technology (fintech) firm. From a buyer perspective, SCF provides an opportunity to finance suppliers on favorable terms increasing their business resilience and overall health. From a supplier perspective, SCF enables opportunities to reduce receivables risks of customers and continue to be financially viable. SCF is not a ‘silver bullet’, but it has been increasingly used since the financial crisis in 2008/2009 to stabilize the liquidity of a supplier organization and interrupt the vicious circle.1  SCF has been incorporated into an organization’s supply chains including customers on the demand side and suppliers on the supply side to assist the organization with its cash flows by securing enough liquidity to ensure supply continuity.2  SCF can help mitigate the impact of the pandemic and can also enable an organization and its suppliers to position themselves for a post pandemic upturn. Over the previous decade practitioners and academics have referred to SCF solutions as a win, win, win for buyers, suppliers and financial service providers (FSPs).3  However, the pandemic has revealed some negative aspects of SCF too.4  For instance, SCF has been accused of aiding buying companies force cash discounts on their suppliers.",
  },
  {
    id: 2,
    title: 'Altaneo nkn',
    img: '../../../public/assets/img/investor3.png',
    oneLine: 'Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of...',
    description:"Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of thousands killed during 2020. It has created economic chaos and caused great damage to firms, their customers, and their suppliers. A critical need for firms is to maintain their financial liquidity to facilitate demand and supply challenges. Across the supply chain, organizations have been forced to reduce staffing to cut costs. These cuts resulted in a dramatic fall in demand for goods and services. For some industrial sectors such as hospitality, tourism and airlines, most revenues were wiped out. Managers had to take drastic decisions to maintain liquidity to survive which resulted in eroding cash reserves, further headcount reductions, reduced expenditures and postponing capital investments. Late customer payments increase in bad debt, and restrictive bank lending practices compounded cash flow problems and decreased liquidity. These problems led to an increased risk of insolvency and resulted in more employee layoffs. Firms found themselves in a downward spiral. A key strategic priority for companies is ensuring that they can meet their net working capital (NWC) needs, where NWC = current assets – current liabilities. Supply chain financing (SCF) is an approach that builds on traditional trade finance solutions to help organizations manage its net working capital more flexibly and at a lower rate of interest than is normally available to a supplier. Suppliers are able to sell their approved invoices to a bank or financial technology (fintech) firm. From a buyer perspective, SCF provides an opportunity to finance suppliers on favorable terms increasing their business resilience and overall health. From a supplier perspective, SCF enables opportunities to reduce receivables risks of customers and continue to be financially viable. SCF is not a ‘silver bullet’, but it has been increasingly used since the financial crisis in 2008/2009 to stabilize the liquidity of a supplier organization and interrupt the vicious circle.1  SCF has been incorporated into an organization’s supply chains including customers on the demand side and suppliers on the supply side to assist the organization with its cash flows by securing enough liquidity to ensure supply continuity.2  SCF can help mitigate the impact of the pandemic and can also enable an organization and its suppliers to position themselves for a post pandemic upturn. Over the previous decade practitioners and academics have referred to SCF solutions as a win, win, win for buyers, suppliers and financial service providers (FSPs).3  However, the pandemic has revealed some negative aspects of SCF too.4  For instance, SCF has been accused of aiding buying companies force cash discounts on their suppliers.",
  },
  {
    id: 3,
    title: 'Altaneo hbjbj',
    img: '../../../public/assets/img/investor3.png',
    oneLine: 'Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of...',
    description:"Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of thousands killed during 2020. It has created economic chaos and caused great damage to firms, their customers, and their suppliers. A critical need for firms is to maintain their financial liquidity to facilitate demand and supply challenges. Across the supply chain, organizations have been forced to reduce staffing to cut costs. These cuts resulted in a dramatic fall in demand for goods and services. For some industrial sectors such as hospitality, tourism and airlines, most revenues were wiped out. Managers had to take drastic decisions to maintain liquidity to survive which resulted in eroding cash reserves, further headcount reductions, reduced expenditures and postponing capital investments. Late customer payments increase in bad debt, and restrictive bank lending practices compounded cash flow problems and decreased liquidity. These problems led to an increased risk of insolvency and resulted in more employee layoffs. Firms found themselves in a downward spiral. A key strategic priority for companies is ensuring that they can meet their net working capital (NWC) needs, where NWC = current assets – current liabilities. Supply chain financing (SCF) is an approach that builds on traditional trade finance solutions to help organizations manage its net working capital more flexibly and at a lower rate of interest than is normally available to a supplier. Suppliers are able to sell their approved invoices to a bank or financial technology (fintech) firm. From a buyer perspective, SCF provides an opportunity to finance suppliers on favorable terms increasing their business resilience and overall health. From a supplier perspective, SCF enables opportunities to reduce receivables risks of customers and continue to be financially viable. SCF is not a ‘silver bullet’, but it has been increasingly used since the financial crisis in 2008/2009 to stabilize the liquidity of a supplier organization and interrupt the vicious circle.1  SCF has been incorporated into an organization’s supply chains including customers on the demand side and suppliers on the supply side to assist the organization with its cash flows by securing enough liquidity to ensure supply continuity.2  SCF can help mitigate the impact of the pandemic and can also enable an organization and its suppliers to position themselves for a post pandemic upturn. Over the previous decade practitioners and academics have referred to SCF solutions as a win, win, win for buyers, suppliers and financial service providers (FSPs).3  However, the pandemic has revealed some negative aspects of SCF too.4  For instance, SCF has been accused of aiding buying companies force cash discounts on their suppliers.",
  },
  {
    id: 4,
    title: 'Altaneo hrms',
    img: '../../../public/assets/img/investor3.png',
    oneLine: 'Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of...',
    description:"Introduction The COVID-19 pandemic has resulted in millions of people infected and hundreds of thousands killed during 2020. It has created economic chaos and caused great damage to firms, their customers, and their suppliers. A critical need for firms is to maintain their financial liquidity to facilitate demand and supply challenges. Across the supply chain, organizations have been forced to reduce staffing to cut costs. These cuts resulted in a dramatic fall in demand for goods and services. For some industrial sectors such as hospitality, tourism and airlines, most revenues were wiped out. Managers had to take drastic decisions to maintain liquidity to survive which resulted in eroding cash reserves, further headcount reductions, reduced expenditures and postponing capital investments. Late customer payments increase in bad debt, and restrictive bank lending practices compounded cash flow problems and decreased liquidity. These problems led to an increased risk of insolvency and resulted in more employee layoffs. Firms found themselves in a downward spiral. A key strategic priority for companies is ensuring that they can meet their net working capital (NWC) needs, where NWC = current assets – current liabilities. Supply chain financing (SCF) is an approach that builds on traditional trade finance solutions to help organizations manage its net working capital more flexibly and at a lower rate of interest than is normally available to a supplier. Suppliers are able to sell their approved invoices to a bank or financial technology (fintech) firm. From a buyer perspective, SCF provides an opportunity to finance suppliers on favorable terms increasing their business resilience and overall health. From a supplier perspective, SCF enables opportunities to reduce receivables risks of customers and continue to be financially viable. SCF is not a ‘silver bullet’, but it has been increasingly used since the financial crisis in 2008/2009 to stabilize the liquidity of a supplier organization and interrupt the vicious circle.1  SCF has been incorporated into an organization’s supply chains including customers on the demand side and suppliers on the supply side to assist the organization with its cash flows by securing enough liquidity to ensure supply continuity.2  SCF can help mitigate the impact of the pandemic and can also enable an organization and its suppliers to position themselves for a post pandemic upturn. Over the previous decade practitioners and academics have referred to SCF solutions as a win, win, win for buyers, suppliers and financial service providers (FSPs).3  However, the pandemic has revealed some negative aspects of SCF too.4  For instance, SCF has been accused of aiding buying companies force cash discounts on their suppliers.",
  },
]